name: CI

on:
  #push:
   # branches: [ "main" ]
   workflow_dispatch:

jobs:
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: <aws-account-number>.dkr.ecr.<region>.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push Docker images
      # uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          tags: 
          
 
      


